Web-WebReklam/Areas/Admin/Controllers/CitiesController.cs
using ApplicationCore_WebReklam.DTO_s.CityDTO;
using ApplicationCore_WebReklam.DTO_s.VillageDTO;
using ApplicationCore_WebReklam.Entities.Concrete;
using AutoMapper;
using Infrastructure_WebReklam.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web_WebReklam.Areas.Admin.Models;

namespace Web_WebReklam.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class CitiesController : Controller
    {
        private readonly ICityRepository _cityRepository;
        private readonly IMapper _mapper;

        public CitiesController(ICityRepository cityRepository, IMapper mapper)
        {
            _cityRepository = cityRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var cities = await _cityRepository.GetFilteredList
                (
                    select: x =>  new GetCityVM 
                    {
                        Id = x.Id,
                        Name = x.Name,
                        CreatedDate = x.CreatedDate,
                        UpdatedDate = x.UpdatedDate,
                        Status = x.Status
                    },
                    where: x => x.Status != ApplicationCore_WebReklam.Entities.Abstract.Status.Passive
                );

            return View(cities);
        }

        public IActionResult CreateCity() => View();

        [HttpPost]
        public async Task<IActionResult> CreateCity(CreateCityDTO model) 
        {
            if (ModelState.IsValid)
            {
                var city = _mapper.Map<City>(model);
                await _cityRepository.AddAsync(city);
                return RedirectToAction("Index");   
            }

            return View(model);
        }
        public async Task<IActionResult> UpdateCity(int id)
        {
            if (id > 0)
            {
                var city = await _cityRepository.GetById(id);
                if (city != null)
                {
                    var model = _mapper.Map<UpdateCityDTO>(city);
                    return View(model);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateCity(UpdateCityDTO model)
        {
            if (ModelState.IsValid)
            {
                var city = _mapper.Map<City>(model);
                await _cityRepository.UpdateAsync(city);
                return RedirectToAction("Index");

            }
            return View(model);
        }
        public async Task<IActionResult> DeleteCity(int id)
        {
            if (id >0)
            {
                var city = await _cityRepository.GetById(id);
                if (city is not null)
                {
                    await _cityRepository.DeleteAsync(city);
                    return RedirectToAction("Index");
                }
                
            }
            return RedirectToAction("Index");
        }
    }
}

Web-WebReklam/Areas/Admin/Controllers/CompanysController.cs
using ApplicationCore_WebReklam.DTO_s.CityDTO;
using ApplicationCore_WebReklam.DTO_s.CompanyDTO;
using ApplicationCore_WebReklam.DTO_s.VillageDTO;
using ApplicationCore_WebReklam.Entities.Concrete;
using AutoMapper;
using Infrastructure_WebReklam.Services.Concrate;
using Infrastructure_WebReklam.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web_WebReklam.Areas.Admin.Models;

namespace Web_WebReklam.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class CompanysController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ICompanyRepository _companyRepository;

        public CompanysController(IMapper mapper, ICompanyRepository companyRepository)
        {
            _mapper = mapper;
            _companyRepository = companyRepository;
        }

        public async Task<IActionResult> Index()
        {
            var company = await _companyRepository.GetFilteredList
                (
                    select: x => new GetCompanyVM
                    {
                        Id = x.Id,
                        Name = x.Name,
                        Description = x.Description,
                        Konum = x.Konum,
                        CreatedDate = x.CreatedDate,
                        UpdatedDate = x.UpdatedDate,
                        Status = x.Status
                    },
                    where: x => x.Status != ApplicationCore_WebReklam.Entities.Abstract.Status.Passive
                );

            return View(company);
        }
        public IActionResult CreateCompany() => View();

        [HttpPost]
        public async Task<IActionResult> CreateCompany(CreateCompanyDTO model)
        {
            if (ModelState.IsValid)
            {
                var company = _mapper.Map<Company>(model);
                await _companyRepository.AddAsync(company);
                return RedirectToAction("Index");
            }

            return View(model);
        }
        public async Task<IActionResult> UpdateCompany(int id)
        {
            if (id > 0)
            {
                var company = await _companyRepository.GetById(id);
                if (company != null)
                {
                    var model = _mapper.Map<UpdateCompanyDTO>(company);
                    return View(model);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateCompany(UpdateCompanyDTO model)
        {
            if (ModelState.IsValid)
            {
                var company = _mapper.Map<Company>(model);
                await _companyRepository.UpdateAsync(company);
                return RedirectToAction("Index");

            }
            return View(model);
        }
        public async Task<IActionResult> DeleteCompany(int id)
        {
            if (id > 0)
            {
                var company = await _companyRepository.GetById(id);
                if (company is not null)
                {
                    await _companyRepository.DeleteAsync(company);
                    return RedirectToAction("Index");
                }

            }
            return RedirectToAction("Index");
        }
    }
}
 

Web-WebReklam/Areas/Admin/Controllers/UserController.cs
using ApplicationCore_WebReklam.Entities.UserEntities.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web_WebReklam.Areas.Admin.Models;

namespace Web_WebReklam.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        readonly UserManager<AppUser> _userManager;
        public UserController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.Where(x => x.Status != ApplicationCore_WebReklam.Entities.Abstract.Status.Passive).ToListAsync();

            return View(users);

        }
    }
}

Web-WebReklam/Controllers/FormController.cs
using ApplicationCore_WebReklam.DTO_s.RequestFormDTO;
using ApplicationCore_WebReklam.Entities.Concrete;
using AutoMapper;
using Infrastructure_WebReklam.Services.Concrate;
using Infrastructure_WebReklam.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Web_WebReklam.Controllers
{
    public class FormController : Controller
    {
        private readonly IRequestFormRepository _requestFormRepository;
        private readonly IMapper _mapper;

        public FormController(IRequestFormRepository requestFormRepository, IMapper mapper)
        {
            _requestFormRepository = requestFormRepository;
            _mapper = mapper;
        }



        public IActionResult GetForm() => View();

        [HttpPost]
        public async Task<IActionResult> GetForm(CreateRequestFormDTO model ) 
        {
            if (ModelState.IsValid)
            {
                var request = _mapper.Map<RequestForm>(model);
                await _requestFormRepository.AddAsync(request);
                return RedirectToAction("Index","Home");
            }

            return View(model);
            
        }
        public IActionResult Index()
        {
            return View();
        }


    }
}

Web-WebReklam/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_WebReklam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web_WebReklam.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web_WebReklam</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Cities" asp-action="Index">Şehirler</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Villages" asp-action="Index">İlçeler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Designers" asp-action="Index">Tasarımcılar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Companys" asp-action="Index">Şirketler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">Üyeler</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Form" asp-action="Index">Talepler</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Web_WebReklam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>