Web-WebReklam/Areas/Admin/Controllers/VillagesController.cs
using ApplicationCore_WebReklam.DTO_s.CityDTO;
using ApplicationCore_WebReklam.DTO_s.VillageDTO;
using ApplicationCore_WebReklam.Entities.Concrete;
using AutoMapper;
using Infrastructure_WebReklam.Services.Concrate;
using Infrastructure_WebReklam.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web_WebReklam.Areas.Admin.Models;

namespace Web_WebReklam.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class VillagesController : Controller
    {
        private readonly IVillageRepository _villageRepository;
        private readonly IMapper _mapper;

        public VillagesController(IVillageRepository villageRepository, IMapper mapper)
        {
            _villageRepository = villageRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var villages = await _villageRepository.GetFilteredList
                (
                    select: x => new GetVillageVM
                    {
                        Id = x.Id,
                        Name = x.Name,
                        CreatedDate = x.CreatedDate,
                        UpdatedDate = x.UpdatedDate,
                        Status = x.Status
                    },
                    where: x => x.Status != ApplicationCore_WebReklam.Entities.Abstract.Status.Passive
                );

            return View(villages);
        }

        public IActionResult CreateVillage() => View();

        [HttpPost]
        public async Task<IActionResult> CreateVillage(CreateVillageDTO model)
        {
            if (ModelState.IsValid)
            {
                var village = _mapper.Map<Village>(model);
                await _villageRepository.AddAsync(village);
                return RedirectToAction("Index");
            }

            return View(model);
        }
        public async Task<IActionResult> UpdateVillage(int id)
        {
            if (id > 0)
            {
                var village = await _villageRepository.GetById(id);
                if (village != null)
                {
                    var model = _mapper.Map<UpdateVillageDTO>(village);
                    return View(model);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateVillage(UpdateVillageDTO model)
        {
            if (ModelState.IsValid)
            {
                var village = _mapper.Map<Village>(model);
                await _villageRepository.UpdateAsync(village);
                return RedirectToAction("Index");

            }
            return View(model);
        }
        public async Task<IActionResult> DeleteVillage(int id)
        {
            if (id > 0)
            {
                var village = await _villageRepository.GetById(id);
                if (village is not null)
                {
                    await _villageRepository.DeleteAsync(village);
                    return RedirectToAction("Index");
                }

            }
            return RedirectToAction("Index");
        }
    }
}

Web-WebReklam/Areas/Admin/Views/Villages/CreateVillage.cshtml
@{
    ViewData["Title"] = "CreateVillage";
}
@model CreateVillageDTO

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">İlçe Ekle</h3>
            </div>
            <form asp-action="CreateVillage" method="post">
                <div class="card-body">
                    <div>
                        <label asp-for="Name" class="form-label"></label>
                        <input asp-for="Name" class="form-control" placeholder="Lütfen ilçe adı giriniz..." />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-footer" style="height:50px;">
                    <div>
                        <button type="submit" class="btn btn-outline-success float-end">Kaydet</button>
                        <a asp-controller="Villages" asp-action="Index" class="btn btn-outline-info float-start">Geri Dön</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Web-WebReklam/Areas/Admin/Views/Villages/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<GetVillageVM>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">İlçe Listesi</h3>
            </div>
            <div class="card-body">
                <div class="table table-responsive table-responsive-sm">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>İlçe Adı</th>
                                <th>Durum</th>
                                <th>Eklenme Tarihi</th>
                                <th>Güncellenme Tarihi</th>
                                <th>Güncelle</th>
                                <th>Sil</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var Village in Model)
                            {
                                <tr>
                                    <td>@Village.Id</td>
                                    <td>@Village.Name</td>
                                    <td>@Village.Status</td>
                                    <td>@Village.CreatedDate</td>
                                    @if (Village.UpdatedDate != null)
                                    {
                                        <td>@Village.UpdatedDate</td>
                                    }
                                    else
                                    {
                                        <td> - </td>
                                    }
                                    <td>
                                        <a asp-controller="Villages" asp-action="UpdateVillage" asp-route-id="@Village.Id" class="btn btn-outline-primary">Güncelle</a>
                                    </td>
                                    <td>
                                        <!-- Button trigger modal -->
                                        <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal-@Village.Id">
                                            Sil
                                        </button>

                                        <!-- Modal -->
                                        <div class="modal fade" id="exampleModal-@Village.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Silme Uyarısı</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        @Village.Name İlçesini silmek istediğinize emin misiniz?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">İptal</button>
                                                        <a asp-controller="Villages" asp-action="DeleteVillage" asp-route-id="@Village.Id" class="btn btn-danger">Sil</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a asp-controller="Villages" asp-action="CreateVillage" class="btn btn-outline-dark d-block">Yeni İlçe Ekle</a>
            </div>
        </div>
    </div>
</div>

Web-WebReklam/Areas/Admin/Views/Villages/UpdateVillage.cshtml
@using ApplicationCore_WebReklam.DTO_s.VillageDTO
@{
    ViewData["Title"] = "Update Village";
}
@model UpdateVillageDTO

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">İlçe Güncelle</h3>
            </div>
            <form asp-action="UpdateVillage">
                <input type="hidden" asp-for="Id" />
                <div class="card-body">
                    <div>
                        <label asp-for="Name" class="form-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="card-footer" style="height:50px;">
                    <button type="submit" class="btn btn-outline-primary float-end">Kaydet</button>
                    <a asp-controller="Villages" asp-action="Index" class="btn btn-outline-secondary float-start">Geri Dön</a>
                </div>
            </form>
        </div>
    </div>
</div>