Web-WebReklam/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Web_WebReklam.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web-WebReklam/Controllers/FormController.cs
using ApplicationCore_WebReklam.DTO_s.RequestFormDTO;
using ApplicationCore_WebReklam.Entities.Concrete;
using AutoMapper;
using Infrastructure_WebReklam.Services.Concrate;
using Infrastructure_WebReklam.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Web_WebReklam.Controllers
{
    public class FormController : Controller
    {
        private readonly IRequestFormRepository _requestFormRepository;
        private readonly IMapper _mapper;

        public FormController(IRequestFormRepository requestFormRepository, IMapper mapper)
        {
            _requestFormRepository = requestFormRepository;
            _mapper = mapper;
        }



        public IActionResult GetForm() => View();

        [HttpPost]
        public async Task<IActionResult> GetForm(CreateRequestFormDTO model ) 
        {
            if (ModelState.IsValid)
            {
                var request = _mapper.Map<RequestForm>(model);
                await _requestFormRepository.AddAsync(request);
                return RedirectToAction("Index","Home");
            }

            return View(model);
            
        }
        public IActionResult Index()
        {
            return View();
        }


    }
}

Web-WebReklam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_WebReklam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web_WebReklam.styles.css" asp-append-version="true" />

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/jquery.ajaxform.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebReklam</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Form" asp-action="GetForm">Talep Formu</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class=" btn btn-outline-secondary nav-link text-dark" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin Panel</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>